/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    structure: Structure;
    media: Media;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password: string;
}
export interface Structure {
  id: string;
  name?: string;
  structure_type?: ('csapa' | 'caarud' | 'chs' | 'chu' | 'chrs' | 'ccas' | 'am' | 'ah' | 'other')[];
  day_night_care?: 'day_night_care' | 'day_care' | 'night_care';
  opening_days?: {
    monday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    tuesday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    wednesday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    thursday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    friday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    saturday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
    sunday?: {
      start_hour_am?: number;
      end_hour_am?: number;
      start_hour_pm?: number;
      end_hour_pm?: number;
    };
  };
  description?: string;
  contact_phone?: string;
  contact_email?: string;
  website?: string;
  address?: string;
  city?: string;
  country?: string;
  postal_code?: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number];
  additional_info?: string;
  capacity_pets?: number;
  capacity_humans?: number;
  people_access_conditions?: {
    conditions?: (
      | 'adapted_when_psychological_problems'
      | 'on_means_tested'
      | 'by_appointment_only'
      | 'free_access'
      | 'participation_requested_for_hosting'
      | 'participation_requested_for_care'
      | 'presence_of_children'
      | 'unaccompanied_minors_accepted'
      | 'couples_accepted'
      | 'adapted_for_reduced_mobility'
      | 'adapted_when_illnesses_and_infections'
      | 'identity_document_mandatory'
      | 'proof_of_income_mandatory'
    )[];
    referral_needed?: ('no' | '115' | 'siao' | 'social_samu' | 'vet')[];
    additional_information?: string;
    max_pets_number_per_person?: number;
    age_restriction_min?: number;
    age_restriction_max?: number;
  };
  pets_access_conditions?: {
    conditions?: (
      | 'sterilized_mandatory'
      | 'access_to_common_areas_allowed'
      | 'short_leash_mandatory'
      | 'muzzle_mandatory'
      | 'up_to_date_health_record_mandatory'
      | 'must_stay_in_the_yard'
      | 'must_remain_in_a_cage'
      | 'dewormed_mandatory'
      | 'identified_mandatory'
      | 'up_to_date_vaccinations_mandatory'
      | 'treated_against_fleas_and_ticks_mandatory'
      | 'can_sleep_with_human'
      | 'big_dogs_allowed'
      | 'pet_type_accepted'
      | 'additional_information'
    )[];
    pet_type_accepted?: 'all' | 'dogs' | 'cats' | 'dogs_and_cats';
    additional_information?: string;
  };
  human_services?: {
    health?: {
      doctor?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      nurse?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      psychologist?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      social_services?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    commodities?: {
      wc?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      shower?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      laveries?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      bagagerie?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      loading_battery?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      vestiaire?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    housing?: {
      solo?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      with_pets?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      couple?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      family?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    food?: {
      alimentary_help?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      restaurant_snack?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    other_services?: {
      traineeship?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      formation?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
  };
  pets_services?: {
    health?: {
      vet?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      surgery?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      dental_care?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      parasytic_treatment?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      vaccination?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      food?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    keeping?: {
      foster_family?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      kennel?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
    other_services?: {
      identity?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
      behaviour?: {
        available?: boolean;
        additional_info?: string;
        opening_hours?: {
          monday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          tuesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          wednesday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          thursday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          friday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          saturday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
          sunday?: {
            start_hour_am?: number;
            end_hour_am?: number;
            start_hour_pm?: number;
            end_hour_pm?: number;
          };
        };
      };
    };
  };
  picture?: {
    image: string | Media;
    picture_description?: string;
    picture_name?: string;
    id?: string;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Media {
  id: string;
  alt?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    card?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    tablet?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string;
  batch?: number;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes {
    collections: {
      'users': User
      'structure': Structure
      'media': Media
      'payload-preferences': PayloadPreference
      'payload-migrations': PayloadMigration
    }

  }
}